# nginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    trivy-operator.aquasecurity.github.io/enabled: "true"
spec:
  containers:
    - name: nginx
      image: nginx:1.21

