apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trivy-operator
  namespace: trivy-system
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: trivy-operator
  namespaceSelector:
    matchNames:
      - trivy-system
  endpoints:
    - port: http
      interval: 30s

